project: x77
queue: normal
walltime: 05:00:00
jobname: jobname
ncpus: 1234
jobfs: 10GB
shortpath: /scratch/nm03

model: mom6
input:
    - path_to_input_files

## You'll need to provide your own executable. If on gadi, you can request access to this one
## but beware, ACCESS-NRI isn't actively maintaining an FMS based executable since they now
## work with NUOPC. See the rOM3 setup instead for a better maintained NUOPC based 
## regional mom6 run on Gadi / NCI
exe: /g/data/ik11/mom_executables/jan2024-latest-everything

collate: false
#runlog: true
storage:
  gdata:
    - ua8
    - x77
    - ik11

mpi:
  module: openmpi/4.1.2

